# Generated by Django 4.2.3 on 2023-10-27 05:03

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('SK_departamento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=256, null=True, verbose_name='nombre del Departamento')),
                ('codigo', models.CharField(max_length=2, null=True, verbose_name='codigo Departamento')),
            ],
            options={
                'db_table': 'departamento',
            },
        ),
        migrations.CreateModel(
            name='DetallePlanilla',
            fields=[
                ('SK_detallePlanilla', models.AutoField(primary_key=True, serialize=False)),
                ('ISSS', models.CharField(max_length=10, null=True, verbose_name='ISSS')),
                ('AFP', models.CharField(max_length=10, null=True, verbose_name='AFP')),
                ('RENTA', models.CharField(max_length=10, null=True, verbose_name='Renta')),
                ('Otras_deducciones', models.CharField(max_length=10, null=True, verbose_name='otras deducciones')),
                ('Liquido_pagar', models.CharField(max_length=50, null=True, verbose_name='Salario Final')),
            ],
            options={
                'db_table': 'detallePlanilla',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256, null=True, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=256, null=True, verbose_name='Apellido')),
                ('documento', models.CharField(max_length=256, null=True, verbose_name='Documento')),
                ('direccion', models.CharField(max_length=100, null=True, verbose_name='Direccion')),
                ('telefono', models.CharField(max_length=15, null=True, verbose_name='Telefono')),
                ('cargo', models.CharField(max_length=100, null=True, verbose_name='Ingrese cargo del empleado')),
            ],
            options={
                'db_table': 'empleado',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('SK_empresa', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=256, null=True, verbose_name='Nombre')),
                ('nombre_comercial', models.CharField(max_length=256, null=True, verbose_name='Nombre comercial')),
                ('nit', models.CharField(max_length=256, null=True, verbose_name='NIT de la empresa')),
                ('act_eco', models.CharField(max_length=256, null=True, verbose_name='Actividad economica')),
                ('direccion', models.CharField(max_length=100, null=True, verbose_name='Direccion')),
                ('telefono', models.CharField(max_length=15, null=True, verbose_name='Telefono')),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='Planilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_planilla', models.DateField(verbose_name='')),
                ('dias_trabajados', models.CharField(max_length=10, null=True, verbose_name='cantidad de dias trabajados')),
                ('horas_extras', models.CharField(max_length=10, null=True, verbose_name='cantidad de horas extras')),
                ('FK_empleado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myadmin.empleado')),
            ],
            options={
                'db_table': 'planilla',
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('SK_municipio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, null=True, verbose_name='Nombre del municipio')),
                ('FK_departamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='myadmin.departamento')),
            ],
            options={
                'db_table': 'municipio',
            },
        ),
        migrations.AddField(
            model_name='empleado',
            name='FK_municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.municipio'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('SK_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_contratacion', models.DateField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'usuario',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
