# Generated by Django 4.2.3 on 2023-10-29 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='codigo',
            field=models.CharField(max_length=2, null=True, verbose_name='codigo municipio'),
        ),
    ]
