# Generated by Django 4.2.3 on 2023-10-29 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_municipio_codigo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planilla',
            name='FK_empleado',
        ),
        migrations.RemoveField(
            model_name='planilla',
            name='dias_trabajados',
        ),
        migrations.RemoveField(
            model_name='planilla',
            name='horas_extras',
        ),
        migrations.AddField(
            model_name='detalleplanilla',
            name='FK_empleado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myadmin.empleado'),
        ),
        migrations.AddField(
            model_name='detalleplanilla',
            name='Fk_planilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='myadmin.planilla', verbose_name='planilla'),
        ),
        migrations.AddField(
            model_name='detalleplanilla',
            name='dias_trabajados',
            field=models.CharField(max_length=10, null=True, verbose_name='cantidad de dias trabajados'),
        ),
        migrations.AddField(
            model_name='detalleplanilla',
            name='horas_extras',
            field=models.CharField(max_length=10, null=True, verbose_name='cantidad de horas extras'),
        ),
    ]
