# Generated by Django 4.2.3 on 2023-10-29 23:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_remove_planilla_fk_empleado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleplanilla',
            name='fecha_emision',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
