# Generated by Django 4.2.3 on 2023-10-29 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_detalleplanilla_fecha_emision'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='salario_base',
            field=models.DecimalField(decimal_places=4, default=365, max_digits=10),
            preserve_default=False,
        ),
    ]
