# Generated by Django 4.2.3 on 2023-10-31 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0005_empleado_salario_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='fk_usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
